### ISSUE TITLE
Permutation tests occasionally fail

### ISSUE THREAD

**Issue by ejolly** [ljchang/nltools#132]
This [line](https://github.com/ljchang/nltools/blob/master/nltools/tests/test_stats.py#L21) specifically. At least locally, sometimes the correlation is between 0.3 < r < 0.4. Not sure if this is something from how the data is simulated or the correlation itself.

**Comment by ljchang** [comment]
we can drop the threshold or add more data to tighten it up.

**Comment by ljchang** [comment]
I added more data to test.  hopefully, this is fixed now.
