### ISSUE TITLE
predict() does not correct for unbalanced classes in dataset

### ISSUE THREAD

**Issue by jeroenvanbaar** [ljchang/nltools#143]
Would be nice to have support for balancing classes in dataset when building svm

**Comment by ejolly** [comment]
This should work if you pass sklearn style `kwargs` to the method. For example:

`dat.predict(algorithm='svm',cv_dict={'type':'kfolds','n_fold':5), {'class_weight':'balanced'})` 

The `{'class_weight':'balanced'}` part is a dictionary specified according to the sklearn spec for a particular algorithm, e.g. in this case [SVM](http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html)

**Comment by jeroenvanbaar** [comment]
You're right, that works. Actually figured it out a little while ago, should've closed the issue, sorry! And thanks!
