### ISSUE TITLE
error in loading data using Brain_Data()

### ISSUE THREAD

**Issue by kristinarapuano** [ljchang/nltools#153]
Loaded dataset returns error message: AttributeError: 'Nifti1Image' object has no attribute 'rfind'

**Comment by ejolly** [comment]
@kristinarapuano Does this happen with all nifit data or specifically those in 3mm or 2mm resolution? Can you post the code and error message here?

**Comment by ljchang** [comment]
I'm not replicating this either and also I don't think we have merged the 2mm and 3mm to the main repo yet.

**Comment by ejolly** [comment]
@ljchang I'm reasonably confident that this was a version issue that @kristinarapuano was experiencing. But just do be sure, we should add a test for the `Brain_Data.__repr__ `which is where it was previously failing

**Comment by ljchang** [comment]
fixed in PR #149
