### ISSUE TITLE
Error in Design_matrix.append for more than two runs

### ISSUE THREAD

**Issue by elvandy** [ljchang/nltools#154]
The addIntercept won't work if you want to append more than 2 runs.

**Comment by ejolly** [comment]
Specifically update intercept checking code to handle concatenating design-matrix A that has more than one run (i.e. multiple intercepts), with design-matrix B that has it's own intercept or doesn't. Currently assumes that A only has a single intercept.

**Comment by ejolly** [comment]
Also need to fix this for run-specific nuisance regressors, polynomial trends, etc
