### ISSUE TITLE
Refactor trim and winsorize into a single function

### ISSUE THREAD

**Issue by ejolly** [ljchang/nltools#158]
They're 99% identical except for 2 lines. Good idea to reduce redundancy and potential for errors. If you want to keep them as separate function can borrow what the sklearn or nilearn folks do and make aliases @jcheong0428 :
```
def trim(data,options):
      return _transform(data,options,mode='trim')

def winsorize(data,options):
     return _transform(data,options,mode='winsorize')

def _transform(data,options):
    '''This isn't ever exposed to the user but called by other functions.''''
     
    #All the shared code
    #
    #
    #    
    if mode == 'trim':
        #Replace with nans
    elif mode == 'winsorize':
        #Replace with cutoffs

**Comment by ljchang** [comment]
I agree with @ejolly, no need to have two separate functions for this.  I propose to get rid of trim entirely.  Just add a flag on the winsorize to replace with nans.  replace_with_cutoff = False would make sense to convert to nans.

**Comment by ljchang** [comment]
@jcheong0428:  Sorry, I think I just removed trim with my last PR #161.  Are you okay with replace_with_cutoff = False resulting in filling with NaNs?

**Comment by ljchang** [comment]
This is related to #192
