### ISSUE TITLE
nltools.stats.downsample returns 1-indexed dataframe

### ISSUE THREAD

**Issue by ejolly** [ljchang/nltools#164]
This is a confusing and made me thing something wrong was happening in the downsampling making it seem off. @ljchang is there any reason not to use the groupby trick starting from 0 instead of 1 in this [line](https://github.com/ljchang/nltools/blob/master/nltools/stats.py#L318)?

Alternatively we could just to a `.reset_index(drop=True)` in this [line](https://github.com/ljchang/nltools/blob/master/nltools/stats.py#L323) and the `.median()` line

**Comment by jcheong0428** [comment]
For some reason I thought we fixed it because it threw an error but looks like it was coded to start from 1 from the start. Think it's fine to reset index before returning.

**Comment by ljchang** [comment]
@ejolly Is this fixed now in PR #149

**Comment by ejolly** [comment]
Fixed in PR #149
