### ISSUE TITLE
Brain_Data slicing is broken on Python 2.7

### ISSUE THREAD

**Issue by ejolly** [ljchang/nltools#165]
Arg @ljchang your commit https://github.com/ljchang/nltools/commit/d6e0c9e14a8a180499261fb58574d4780a5535c6#diff-0c276a25446c051bdca2443268c0bd00
to "make logic tests pass" broke basic slicing, e.g.

```
dat = Brain_Data(mydata.nii.gz) #nifti with 40 images
dat[:10] #Produces IndexError: arrays used as indices must be of integer (or boolean) type
```

This is the only commit that I can get working https://github.com/ljchang/nltools/commit/f1738bff1334dfd4dd99501cc1e099feb702396e

**Comment by ljchang** [comment]
actually, regex for a colon should work.  Let me try that.

**Comment by ljchang** [comment]
turns out there is a `slice` class, which made this easier than I expected.

**Comment by ljchang** [comment]
fixed.
