### ISSUE TITLE
Pip installation of 0.3.4 fails - No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by mslw** [ljchang/nltools#180]
Trying to install nltools using pip (Windows, Python 3.6, pip 9.0.1) results with the following:

PS C:\Users\Michal> pip install nltools
Collecting nltools
  Downloading nltools-0.3.4.tar.gz (3.2MB)
    100% |████████████████████████████████| 3.2MB 397kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Michal\AppData\Local\Temp\pip-build-hrmd36bs\nltools\setup.py", line 10, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

Running `pip install nltools`==0.3.2 works without any issues. Could this be an issue with the latest installer available from PyPI?

**Comment by ljchang** [comment]
Sorry about that.  We don't have any tests for windows. 

@ejolly, can you fix this.  I think it is caused by the new way you are importing the requirements file.  Seems like we need to figure out a way to make a universal platform independent path to the file.

**Comment by ejolly** [comment]
@ljchang Is the requirements.txt file listed in the MANIFEST.in for Pypi (don't see it here in github)? That should solve this file not found issue. Otherwise we can alternatively use 'find_packages()' in the 'setup.py' file.

**Comment by ljchang** [comment]
fixed
