### ISSUE TITLE
Fix tests for 3mm resolution

### ISSUE THREAD

**Issue by ejolly** [ljchang/nltools#209]
@ljchang Left a note for you in a previous commit [here](https://github.com/ljchang/nltools/commit/ea74b5cd2ae93ad62bd3a00131d6f7a959e7abe6#diff-a38dd933e0bb574e2a47e6d547da7848), but we're no longer testing 3mm templates by doing this. We need to explicitly set the template resolution or write a separate function

**Comment by ejolly** [comment]
Fix for this is now part of PR https://github.com/ljchang/nltools/pull/210

**Comment by ejolly** [comment]
Reminder: we've turned off tests of 3mm as of now.

**Comment by ljchang** [comment]
I'm going to close this for now, but we should revisit at some point.
