### ISSUE TITLE
Passing list to Brain_Data created 3d array

### ISSUE THREAD

**Issue by ejolly** [ljchang/nltools#214]
For some reason loading files when given a list doesn't concatenate during loading properly. 
For example if I have 3 niftis with 100 TRs each in a list like:

`file_list = [pathToA,pathToB,pathToC]`

I expect `dat = Brain_Data(file_list)` to be 300 x numVox. Instead it returns a 3 x 100 x numVoxels `Brain_Data` instance.

Did this functionality change in a commit somewhere @ljchang ?

**Comment by ljchang** [comment]
Hmm... Not sure.  The only thing I remember changing related to that part of the code is making it so that Brain_Data([list of Brain_Data]) would concatenate the images, which is pretty hands.  Hopefully, I didn't screw something up for the original list functionality.

**Comment by ljchang** [comment]
Fixed in #215
