### ISSUE TITLE
Change input from sample length to sampling rate in Design_Matrix.sampling_rate

### ISSUE THREAD

**Issue by ljchang** [ljchang/nltools#228]
Looks like sampling_rate is inputting the sample length instead of sampling_rate, which ought to be in hertz like all of our other functions.  We should change this to be consistent.  Will need to update any method that depends on sampling_rate.

**Comment by ejolly** [comment]
Coming in a PR. All methods/functions in `Design_Matrix`, `Brain_Data` will take `sampling_freq` as their argument with the expectation that this is reflects hertz. This is consistent with the default in our stats functions.
