### ISSUE TITLE
The workaround to the matplotlib/framework issue

### ISSUE THREAD

**Issue by enfascination** [ljchang/nltools#229]
FYI, like others, I ran into `RuntimeError: Python is not installed as a framework` when importing nltools within a conda enviroment.

The most efficient workaround is 
```
conda install python.app
mkdir -p ~/anaconda/envs/<YOURENVNAME>/etc/conda/activate.d
touch ~/anaconda/envs/<YOURENVNAME>/etc/conda/activate.d/env_vars.sh
cat 'alias python=pythonw' >> ~/anaconda/envs/<YOURENVNAME>/etc/conda/activate.d/env_vars.sh
```

I haven't seen the last few steps ([see here](https://conda.io/docs/user-guide/tasks/manage-environments.html#saving-environment-variables)) elsewhere, so I thought I'd share.

**Comment by ejolly** [comment]
This is a matplotlib vs macOS issue not strictly a python issue. You don't need to do what you did above. Instead a much simpler (and the recommended) fix is:
1. `conda install matplotlib` or `pip install matplotlib` 
2. In your home directory there will be a folder `~/.matplotlib`, if not make one.
3. Within that folder create a file called `matplotlibrc` and put the following inside:
`backend: TkAgg`
4. Restart/rerun any python stuff depending on matplotlib
